/* file-get-contents.c generated by valac 0.22.1, the Vala compiler
 * generated from file-get-contents.vala, do not modify */

/*https://wiki.gnome.org/Projects/Vala/BasicSample*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <stdio.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))



void _vala_main (void);


void _vala_main (void) {
	GError * _inner_error_ = NULL;
	{
		gchar* file = NULL;
		gchar* _tmp0_ = NULL;
		gchar* content = NULL;
		gsize size = 0UL;
		gchar* _tmp1_ = NULL;
		gsize _tmp2_ = 0UL;
		FILE* _tmp3_ = NULL;
		_tmp0_ = g_strdup ("data.txt");
		file = _tmp0_;
		g_file_get_contents (file, &_tmp1_, &_tmp2_, &_inner_error_);
		_g_free0 (content);
		content = _tmp1_;
		size = _tmp2_;
		if (_inner_error_ != NULL) {
			_g_free0 (content);
			_g_free0 (file);
			if (_inner_error_->domain == G_FILE_ERROR) {
				goto __catch0_g_file_error;
			}
			_g_free0 (content);
			_g_free0 (file);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_tmp3_ = stdout;
		fprintf (_tmp3_, "%s\n", content);
		_g_free0 (content);
		_g_free0 (file);
	}
	goto __finally0;
	__catch0_g_file_error:
	{
		GError* e = NULL;
		FILE* _tmp4_ = NULL;
		GError* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = stderr;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		fprintf (_tmp4_, "%s\n", _tmp6_);
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


int main (int argc, char ** argv) {
	g_type_init ();
	_vala_main ();
	return 0;
}



